# -*- coding: utf-8 -*-
"""IRIS FLOWER CLASSIFIER.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MuaZHFqJtVpBoRxjOku_x9L2oIfyqFIh
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
columns_names = ["sepal_length", "sepal_width", "petal_length", "petal_width", "species"]
iris_data=pd.read_csv(url, names=columns_names)

iris_data.head(100)

type(iris_data)

iris_data.iloc[50:100]

iris_data.describe()

sns.pairplot(iris_data,hue="species")
plt.show()

x=iris_data.drop("species",axis=1)
x

y=iris_data["species"]
y

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

x_train

knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train,y_train)

y_pred=knn.predict(x_test)

print("Accuracy:",accuracy_score(y_test,y_pred))

print(classification_report(y_test,y_pred))

x_test.head(2)

new_data=pd.DataFrame({"sepal_length":[5.1],"sepal_width":[3.5],"petal_length":[1.4],"petal_width":[0.2]})

prediction=knn.predict(new_data)

prediction[0]

